spring:
  application:
    name: ViewService
  mvc:
    hidden method:
      filter:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      registerWithEureka: true
      fetchRegistry: true

server:
  port: 8082